# Generated by Django 2.2.16 on 2020-11-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="group",
            new_name="groups",
        ),
    ]
