# Generated by Django 2.2.16 on 2020-11-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20201123_2201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ForeignKey(
                blank=True,
                db_column="group_id",
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_set",
                related_query_name="user",
                to="auth.Group",
                verbose_name="group",
            ),
        ),
    ]
