# Generated by Django 2.2.16 on 2020-12-18 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="Project name need to be atleast 2 characters long",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=10,
                                message="Project description must be atleast 10 characters long",
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dependency", models.CharField(default=None, max_length=255)),
                ("expected_completion_date", models.DateField()),
                ("actual_completion_date", models.DateField(null=True)),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskRemarksHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_remarks_history",
            },
        ),
    ]
