# Generated by Django 2.2.16 on 2020-12-27 16:04

import django.core.validators
from django.db import migrations, models
import itrack.model_field_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="None name need to be atleast 2 characters long",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=10,
                                message="None description must be atleast 10 characters long",
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("dependency", models.CharField(max_length=255, null=True)),
                (
                    "expected_completion_date",
                    models.DateField(
                        validators=[itrack.model_field_validation.past_date_validator]
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        null=True,
                        validators=[itrack.model_field_validation.past_date_validator],
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskRemarksHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "task_remarks_history",
            },
        ),
    ]
