# Generated by Django 2.2.16 on 2020-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_auto_20201218_2124"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
