# Generated by Django 2.2.16 on 2020-12-20 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_task_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=10,
                        message="None description must be atleast 10 characters long",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=2,
                        message="None name need to be atleast 2 characters long",
                    )
                ],
            ),
        ),
    ]
