# Generated by Django 2.2.16 on 2020-12-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_auto_20201129_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependency",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
