# Generated by Django 2.2.16 on 2020-12-20 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2,
                                message="None name need to be atleast 2 characters long",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=10,
                                message="None description must be atleast 10 characters long",
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "project",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRemarksHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "project_remarks_history",
                "ordering": ["id"],
            },
        ),
    ]
