# Generated by Django 2.2.16 on 2020-10-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRemarksHistory",
            fields=[
                (
                    "abstractremarkshistory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shared.AbstractRemarksHistory",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.Project",
                    ),
                ),
            ],
            options={
                "db_table": "project_remarks_history",
            },
            bases=("shared.abstractremarkshistory",),
        ),
    ]
