# Generated by Django 2.2.16 on 2020-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_belongs_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
