# Generated by Django 2.2.16 on 2020-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
