# Generated by Django 2.2.16 on 2020-12-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_todo_is_complete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["-created_at"]},
        ),
    ]
